# Python Data Types and Structures

1.   What are data structures, and why are they important?
*   Data structures in Python are used to store and organize data efficiently.
Common types include lists, tuples, dictionaries, sets, and queues.
They help in accessing, modifying, and managing data quickly and easily.
Choosing the right data structure improves performance and simplifies code.
They are essential for solving problems effectively in programming.



2.  Explain the difference between mutable and immutable data types with examples

*   Mutable data types can be changed after creation, while immutable ones cannot.
List, set and dictionary are examples of mutable types.
String and tuple are immutable types.
Changing a mutable object updates it in place
Example: `my_list[0] = 10` works, but `my_str[0] = 'a'` gives an error.


3. What are the main differences between lists and tuples in Python ?

*   Lists are mutable, meaning their elements can be changed, while tuples are immutable.
Lists use square brackets `[]`, and tuples use parentheses `()`.
Lists are slower but more flexible, suitable for dynamic data.
Tuples are faster and often used for fixed data.


4.  Describe how dictionaries store data in python ?

*    Dictionaries in Python store data as key-value pairs.
Each key is unique and maps to a specific value.
They are unordered before Python 3.7, but ordered from Python 3.7 onward.
Example: my_dict = {"name": "Ajay", "age": 25}
You can access values using keys: my_dict["name"].

5. Why might you use a set instead of a list in Python ?

*   You might use a set instead of a list in Python when you need to store unique items only. Sets automatically remove duplicates, making them ideal for filtering repeated values. They also offer faster lookup and membership testing compared to lists. Sets are unordered and unindexed, which means they don’t preserve element order. Use a set when uniqueness and speed are more important than order.


6. What is a string in Python, and how is it different from a list ?


*   A string in Python is a sequence of characters used to represent text, like `"hello"`. It is immutable, meaning you can't change its content after creation. A list, on the other hand, is a collection of items (which can be numbers, strings, etc.) and is mutable, so you can add, remove, or change elements. Strings use quotes, while lists use square brackets. Use strings for text, and lists for handling collections of items.


7. How do tuples ensure data integrity in Python ?

*  Tuples ensure data integrity in Python because they are immutable, meaning their values cannot be changed after creation. This makes them ideal for storing fixed collections of data, like coordinates or configuration settings. Since data can’t be modified, it helps prevent accidental changes in your program. Tuples can be used as dictionary keys due to their immutability. Use tuples when you want to keep data safe and constant.


8. What is a hash table, and how does it relate to dictionaries in Python ?

*   A hash table is a data structure that stores key-value pairs using a hashing function to compute an index for each key. In Python, dictionaries are implemented using hash tables. This allows for fast data access, where you can quickly retrieve, add, or delete values by their keys. The hash function ensures that each key maps to a unique index in memory. So, when you use a dictionary in Python, you're actually working with a hash table behind the scenes.


 9. Can lists contain different data types in Python ?


*  Yes, lists in Python can contain different data types. A single list can hold integers, strings, floats, booleans, or even other lists and objects.
This flexibility makes lists powerful for storing mixed data.



10. Explain why strings are immutable in Python ?

*  Strings are immutable in Python because once a string is created, its contents cannot be changed. This design ensures memory efficiency, security, and helps avoid unexpected bugs in programs. For example, if multiple variables reference the same string, changes in one won't affect others. Instead of modifying a string, Python creates a new one when changes are made. This behavior keeps string operations predictable and safe.


11. What advantages do dictionaries offer over lists for certain tasks ?


* Dictionaries offer several advantages over lists for certain tasks. They allow you to store data as key-value pairs, making it easy to access values using meaningful keys instead of numeric indexes. This results in faster lookups, especially for large datasets. Dictionaries are ideal when you need to map relationships, like names to phone numbers. They also support dynamic and unordered data, making them more flexible for real-world modeling than lists.


12. Describe a scenario where using a tuple would be preferable over a list ?

* Using a tuple is preferable when you want to store data that should not change, like a pair of geographic coordinates (latitude, longitude). Since tuples are immutable, the data stays safe from accidental modification. They are also slightly faster and can be used as dictionary keys. For example, you might use tuples to store fixed configuration settings. Choose a tuple when data integrity and performance matter.


13. How do sets handle duplicate values in Python ?

*   Sets in Python automatically remove duplicate values. When you add elements to a set, any repeated items are ignored, and only unique values are stored. For example, `set([1, 2, 2, 3])` will result in `{1, 2, 3}`. This makes sets useful for filtering duplicates from a list. Sets ensure every item appears only once.


14. How does the “in” keyword work differently for lists and dictionaries ?

* The `in` keyword checks for membership, but works differently for lists and dictionaries:

 In lists, `in` checks if a value exists in the list elements.
  Example: `3 in [1, 2, 3]` → `True`

 In dictionaries, `in` checks if a key exists (not values).
  Example: `'name' in {'name': 'Ajay'}` → `True`.
  So, `in` checks values in lists, but keys in dictionaries.

15. Can you modify the elements of a tuple? Explain why or why not

*   No, you cannot modify the elements of a tuple because tuples are immutable in Python. Once a tuple is created, its contents cannot be changed—this includes adding, removing, or updating elements. This immutability helps ensure data integrity and allows tuples to be used as dictionary keys. If you need a collection that can be changed, you should use a list instead. Tuples are best for fixed, unchanging data.


16. What is a nested dictionary, and give an example of its use case ?

*   A nested dictionary is a dictionary that contains another dictionary as a value. It allows you to store complex, structured data in layers.

Example use case: Storing student records, where each student has their own dictionary of details.

students = {
    "ID1": {"name": "Ajay", "age": 20, "grade": "A"},
    "ID2": {"name": "Bijay", "age": 21, "grade": "B"}
}

This makes it easy to access or update data by student ID.


17. Describe the time complexity of accessing elements in a dictionary ?

*   Accessing elements in a dictionary has an average time complexity of O(1) (constant time). This is because dictionaries use a hash table to map keys to values, allowing fast lookups. However, in rare cases like hash collisions, the time complexity can degrade to O(n). But overall, dictionary access is very efficient and much faster than searching through a list.


18. In what situations are lists preferred over dictionaries ?

*   Lists are preferred over dictionaries when you need to store an ordered collection of items where the position (index) matters. They are ideal for tasks like iterating through sequences, maintaining order, or storing simple collections such as numbers or names. Use lists when you don't need key-value pairs or fast lookups by key. Lists are also simpler and use less memory compared to dictionaries. They’re great for stacking, queuing, or grouping items.


19. Why are dictionaries considered unordered, and how does that affect data retrieval ?

*   Dictionaries are considered unordered because they do not store items in a fixed sequence like lists do. Instead, they organize data based on the hash of the keys, not their insertion order. This means you cannot access items by position or index. Data retrieval is done by key, not order, which allows for fast access but not ordered traversal. So, while fast, dictionaries aren’t suited for tasks needing sequence control.


20. Explain the difference between a list and a dictionary in terms of data retrieval.

*   The main difference between a list and a dictionary in terms of data retrieval is how you access the data:

 In a list, you retrieve data using a numeric index (e.g., `my_list[0]`), so the position matters.
 In a dictionary, you retrieve data using a key (e.g., `my_dict["name"]`), so the position doesn't matter.

 Lists are best for ordered sequences, while dictionaries are ideal for fast lookups using meaningful labels.

# Practical questions

In [1]:
# 1. Write a code to create a string with your name and print it
my_name = "chandrakant"
print("My name is", my_name)

My name is chandrakant

In [3]:
# 2. Write a code to find the length of the string "Hello World"

message = "Hello World"
length = len(message)
print(length)

11

In [4]:
# 3. Write a code to slice the first 3 characters from the string "Python Programming"

text = "Python Programming"
sliced = text[:3]
print(sliced)

Pyt

In [5]:
# 4. Write a code to convert the string "hello" to uppercase

text = "hello"
uppercase_text = text.upper()
print(uppercase_text)

HELLO

In [6]:
# 5. Write a code to replace the word "apple" with "orange" in the string "I like apple"

text = "I like apple"
new_text = text.replace("apple", "orange")
print(new_text)

I like orange

In [7]:
# 6. Write a code to create a list with numbers 1 to 5 and print it

numbers = [1, 2, 3, 4, 5]
print(numbers)

[1, 2, 3, 4, 5]

In [8]:
# 7. Write a code to append the number 10 to the list [1, 2, 3, 4]

my_list = [1, 2, 3, 4]
my_list.append(10)
print(my_list)

[1, 2, 3, 4, 10]

In [9]:
# 8. Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]

my_list = [1, 2, 3, 4, 5]
my_list.remove(3)
print(my_list)

[1, 2, 4, 5]

In [11]:
# 9. Write a code to access the second element in the list ['a', 'b', 'c', 'd']

my_list = ['a', 'b', 'c', 'd']
second_element = my_list[1]
print(second_element)

b

In [12]:
# 10. Write a code to reverse the list [10, 20, 30, 40, 50].

list = [10, 20, 30, 40, 50]

list[::-1]

[50, 40, 30, 20, 10]

In [13]:
# 11. Write a code to create a tuple with the elements 100, 200, 300 and print it.

t = (100, 200, 300)
print(t)

(100, 200, 300)

In [14]:
# 12. Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').

t = ('red', 'green', 'blue', 'yellow')
t[-2]

'blue'

In [16]:
# 13. Write a code to find the minimum number in the tuple (10, 20, 5, 15).

t = (10, 20, 5, 15)
min_num = min(t)
print(min_num)

5

In [19]:
# 14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

t = ('dog', 'cat', 'rabbit')

cat_index = t.index("cat")
print(cat_index)

1

In [20]:
# 15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.

fruits = ("apple", "banana", "mango")
if "kiwi" in fruits:
    print("Kiwi is in the tuple.")
else:
    print("Kiwi is not in the tuple.")

Kiwi is not in the tuple.

In [21]:
# 16. Write a code to create a set with the elements 'a', 'b', 'c' and print it.

my_set = {'a', 'b', 'c'}
print(my_set)

{'b', 'a', 'c'}

In [22]:
# 17. Write a code to clear all elements from the set {1, 2, 3, 4, 5}.

my_set = {1, 2, 3, 4, 5}
my_set.clear()
print(my_set)

set()

In [23]:
# 18. Write a code to remove the element 4 from the set {1, 2, 3, 4}.

my_set = {1, 2, 3, 4}
my_set.remove(4)
print(my_set)

{1, 2, 3}

In [25]:
# 19. Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}.

set1 = {1, 2, 3}
set2 = {3, 4, 5}
union_set = set1 | set2
print(union_set)

{1, 2, 3, 4, 5}

In [26]:
# 20.  Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}.

set1 = {1, 2, 3}
set2 = {2, 3, 4}
intersection_set = set1 & set2
print(intersection_set)

{2, 3}

In [27]:
# 21. Write a code to create a dictionary with the keys "name", "age", and "city", and print it

person = {
    "name": "Ajay",
    "age": 25,
    "city": "New Delhi"
}
print(person)

{'name': 'Ajay', 'age': 25, 'city': 'New Delhi'}

In [28]:
# 22. Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.

person = {'name': 'John', 'age': 25}
person['country'] = 'USA'
print(person)

{'name': 'John', 'age': 25, 'country': 'USA'}

In [30]:
# 23. Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.

person = {'name': 'Alice', 'age': 30}
name_value = person['name']
print(name_value)

Alice

In [31]:
# 24. Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.

person = {'name': 'Bob', 'age': 22, 'city': 'New York'}
person.pop('age')
print(person)

{'name': 'Bob', 'city': 'New York'}

In [32]:
# 25. Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.

person = {'name': 'Alice', 'city': 'Paris'}
if 'city' in person:
    print("Key 'city' exists in the dictionary.")
else:
    print("Key 'city' does not exist in the dictionary.")

Key 'city' exists in the dictionary.

In [33]:
# 26. Write a code to create a list, a tuple, and a dictionary, and print them all.

# Creating a list
my_list = [1, 2, 3, 4, 5]

# Creating a tuple
my_tuple = ('apple', 'banana', 'cherry')

# Creating a dictionary
my_dict = {'name': 'John', 'age': 30, 'city': 'London'}

# Printing all
print("List:", my_list)
print("Tuple:", my_tuple)
print("Dictionary:", my_dict)

List: [1, 2, 3, 4, 5]
Tuple: ('apple', 'banana', 'cherry')
Dictionary: {'name': 'John', 'age': 30, 'city': 'London'}

In [43]:
# 27. Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result.(replaced)


random_numbers = [20, 7, 5, 45, 32]


random_numbers.sort()


print( random_numbers)

[5, 7, 20, 32, 45]

In [44]:
# 28. Write a code to create a list with strings and print the element at the third index.

my_list = ["apple", "banana", "cherry", "date", "elderberry"]
print( my_list[3])

date

In [47]:
# 29. Write a code to combine two dictionaries into one and print the result.

dict1 = {'name': 'Alice', 'age': 25}
dict2 = {'city': 'Paris', 'country': 'France'}

combined_dict = {**dict1, **dict2}

print( combined_dict)

{'name': 'Alice', 'age': 25, 'city': 'Paris', 'country': 'France'}

In [48]:
# 30. Write a code to convert a list of strings into a set

string_list = ["apple", "banana", "cherry", "apple"]
string_set = set(string_list)
print("Set:", string_set)

Set: {'apple', 'banana', 'cherry'}